{
  # Generated by vps-facts; verify every value before enabling deployment.
  deploymentReady = true;
  disk = "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi0";
  bootMode = "bios";
  interface = "eth0";
  tailscaleDnsName = "boar-beta.ts.net";

  ipv4 = {
    address = "169.58.106.248";
    prefixLength = 17;
    gateway = "169.58.0.1";
  };
}
