#!/usr/bin/env bash

set -euo pipefail

output="machines/vps/instance.nix"
local_mode=false
requested_disk=""
ssh_args=()

usage() {
  printf '%s\n' "Usage: vps-facts [--local] [--output <file>] [--disk <by-id-path>] [ssh-options] <user@host>"
}

while (($# > 0)); do
  case "$1" in
    --local)
      local_mode=true
      shift
      ;;
    --output)
      [[ $# -ge 2 ]] || { usage >&2; exit 1; }
      output="$2"
      shift 2
      ;;
    --disk)
      [[ $# -ge 2 ]] || { usage >&2; exit 1; }
      requested_disk="$2"
      shift 2
      ;;
    --)
      shift
      ssh_args+=("$@")
      break
      ;;
    *)
      ssh_args+=("$1")
      shift
      ;;
  esac
done

if [[ "$local_mode" == false && ${#ssh_args[@]} -eq 0 ]]; then
  usage >&2
  exit 1
fi

if [[ ! -d "$(dirname "$output")" ]]; then
  printf 'ERROR: output directory does not exist: %s\n' "$(dirname "$output")" >&2
  exit 1
fi

facts_file="$(mktemp)"
output_tmp="$(mktemp "${output}.tmp.XXXXXX")"
cleanup() {
  rm -f "$facts_file" "$output_tmp"
}
trap cleanup EXIT

if [[ "$local_mode" == true ]]; then
  bash @remoteScript@ --machine > "$facts_file"
else
  ssh "${ssh_args[@]}" bash -s -- --machine < @remoteScript@ > "$facts_file"
fi

boot_mode=""
interface=""
address=""
prefix_length=""
gateway=""
disk_links=()
disk_targets=()

while IFS=$'\t' read -r kind name value; do
  case "$kind:$name" in
    FACT:bootMode) boot_mode="$value" ;;
    FACT:interface) interface="$value" ;;
    FACT:address) address="$value" ;;
    FACT:prefixLength) prefix_length="$value" ;;
    FACT:gateway) gateway="$value" ;;
    DISK:*)
      disk_links+=("$name")
      disk_targets+=("$value")
      ;;
  esac
done < "$facts_file"

if [[ "$boot_mode" != "bios" && "$boot_mode" != "uefi" ]]; then
  printf 'ERROR: could not determine boot mode\n' >&2
  exit 1
fi
if [[ ! "$interface" =~ ^[A-Za-z0-9_.:-]+$ ]]; then
  printf 'ERROR: could not determine default network interface\n' >&2
  exit 1
fi
if [[ ! "$address" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  printf 'ERROR: could not determine IPv4 address\n' >&2
  exit 1
fi
if [[ ! "$gateway" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  printf 'ERROR: could not determine IPv4 gateway\n' >&2
  exit 1
fi
if [[ ! "$prefix_length" =~ ^[0-9]+$ ]] || ((prefix_length < 0 || prefix_length > 32)); then
  printf 'ERROR: could not determine IPv4 prefix length\n' >&2
  exit 1
fi
if ((${#disk_links[@]} == 0)); then
  printf 'ERROR: no stable whole-disk IDs found\n' >&2
  exit 1
fi

disk=""
if [[ -n "$requested_disk" ]]; then
  for candidate in "${disk_links[@]}"; do
    if [[ "$candidate" == "$requested_disk" ]]; then
      disk="$candidate"
      break
    fi
  done
  if [[ -z "$disk" ]]; then
    printf 'ERROR: requested disk is not a reported whole-disk ID: %s\n' "$requested_disk" >&2
    exit 1
  fi
else
  unique_targets=()
  for target in "${disk_targets[@]}"; do
    seen=false
    for existing in "${unique_targets[@]}"; do
      [[ "$existing" == "$target" ]] && seen=true
    done
    $seen || unique_targets+=("$target")
  done

  if ((${#unique_targets[@]} != 1)); then
    printf 'ERROR: multiple physical disks found; rerun with --disk <by-id-path>:\n' >&2
    printf '  %s\n' "${disk_links[@]}" >&2
    exit 1
  fi

  best_rank=99
  for candidate in "${disk_links[@]}"; do
    case "${candidate##*/}" in
      wwn-*) rank=1 ;;
      nvme-*) rank=2 ;;
      scsi-*) rank=3 ;;
      virtio-*) rank=4 ;;
      ata-*) rank=5 ;;
      *) rank=10 ;;
    esac
    if ((rank < best_rank)); then
      disk="$candidate"
      best_rank=$rank
    fi
  done
fi

{
  printf '{\n'
  printf '  # Generated by vps-facts; verify every value before enabling deployment.\n'
  printf '  deploymentReady = false;\n'
  printf '  disk = "%s";\n' "$disk"
  printf '  bootMode = "%s";\n' "$boot_mode"
  printf '  interface = "%s";\n' "$interface"
  printf '\n'
  printf '  ipv4 = {\n'
  printf '    address = "%s";\n' "$address"
  printf '    prefixLength = %s;\n' "$prefix_length"
  printf '    gateway = "%s";\n' "$gateway"
  printf '  };\n'
  printf '}\n'
} > "$output_tmp"

chmod 644 "$output_tmp"
mv "$output_tmp" "$output"

printf 'Wrote %s with deploymentReady = false.\n' "$output"
printf 'Verify disk and network values against Contabo, then set deploymentReady = true.\n'
